### PR TITLE
allow trace, connection_timeout, or cache_wsdl options to be set

### PR DESCRIPTION
**Pull request by nopolabs**
I am finding I need a longer connection_timeout to accommodate initial caching of wsdl/xsd files.

### CODE REVIEW

**Comment by nopolabs** [comment]
nevermind, connection_timeout won't help, going to see if I can just download and use the zipped wsdl from netsuite

**Comment by fungku** [comment]
Let me know how that goes. I might want to try that too.

**Comment by nopolabs** [comment]
That looks like the way to go, I downloaded and unzipped http://www.netsuite.com/download/WSDL_v2015_1_0.zip and can provide a relative path to the netsuite.wsdl as the $wsdl parameter to NetSuiteService, much quicker start-up.

**Comment by fungku** [comment]
@nopolabs thanks for the update!

**Comment by nopolabs** [comment]
Hey Ryan,

I just got back to using the netsuie-php library.

My upsert code is now throwing a fault when I try to upsert a list of
vendor records:

  [SoapFault]
  org.xml.sax.SAXException: {urn:
core_2015_1.platform.webservices.netsuite.com}Record is an abstract type
and cannot be instantiated

I need to write a simple test case, but I thought I'd check to see if you
had seen this error before.

Dan


On Fri, May 29, 2015 at 10:53 AM, Ryan Winchester <notifications@github.com>
wrote:

> @nopolabs <https://github.com/nopolabs> thanks for the update!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fungku/netsuite-php/pull/3#issuecomment-106887089>.
>



-- 
Dan Revel
danrevel@gmail.com

**Comment by nopolabs** [comment]
Nevermind, it was my coding error.

I was adding my vendors to $upsertListRequest->records, but it should be
$upsertListRequest->record (no s),
and of course the sax library did not understand my intention.

Cheers,

Dan

On Thu, Jul 30, 2015 at 6:06 PM, Dan Revel <danrevel@gmail.com> wrote:

> Hey Ryan,
>
> I just got back to using the netsuie-php library.
>
> My upsert code is now throwing a fault when I try to upsert a list of
> vendor records:
>
>   [SoapFault]
>   org.xml.sax.SAXException: {urn:
> core_2015_1.platform.webservices.netsuite.com}Record is an abstract type
> and cannot be instantiated
>
> I need to write a simple test case, but I thought I'd check to see if you
> had seen this error before.
>
> Dan
>
>
> On Fri, May 29, 2015 at 10:53 AM, Ryan Winchester <
> notifications@github.com> wrote:
>
>> @nopolabs <https://github.com/nopolabs> thanks for the update!
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/fungku/netsuite-php/pull/3#issuecomment-106887089>.
>>
>
>
>
> --
> Dan Revel
> danrevel@gmail.com
>



-- 
Dan Revel
danrevel@gmail.com

**Comment by fungku** [comment]
@nopolabs - Yeah, I've seen that error before. 

`PEBCAK` ;)

**Pull request closed without merging**
